version: "3"
services:
  backend:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/appoint
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000/
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: appoint
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
