apiVersion: v1
kind: Service
metadata:
  name: playground
spec:
  ports:
    - port: 7681
      targetPort: 7681
  selector:
    app: playground
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: playground
  name: playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: playground
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: playground
    spec:
      containers:
        - image: ubuntu:latest
          name: ubuntu
          command: ["/bin/bash", "-c"]
          args:
            - apt-get update && apt-get install -y ttyd bash && ttyd --writable --client-option cursorBlink=true --client-option fontSize=18 -p 7681 bash
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
status: {}
