name: Build UI-Service

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Trigger only for changes in ui/ folder
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd  # Should be /home/runner/work/appointment/appointment
          echo "List files:"
          ls -R  # Show all files recursively

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ui  # Build from ui/ subdirectory
          push: true
          tags: thanh1994/elearn-ui:latest
